on:
  push:
    branches:
      - master
name: Build & Deploy to ACI
env:
  LOCATION: centralindia
  RESOURCE_GROUP: ShareFreeAlphaARG
  STORAGE_ACCOUNT: sharefreealphaasa
  STORAGE_CONTAINER: sharefreealphaasc
  CONTAINER_REGISTERY: sharefreealphaacr
  KEY_VAULT: ShareFreeAlphaAKV
  APP_NAME: share-free-ui
  WEBAPP_NAME: sharefreeuialpha
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout GitHub Action
          uses: actions/checkout@master
          
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set default location
          run: |
            az configure --defaults location=${{ env.LOCATION }}
            az configure --defaults group=${{ env.RESOURCE_GROUP }}

        - name: Create environment.ts
          run: |
            touch src/environments/environment.ts
            printf '${{ secrets.ALPHA_UI_ENV }}' >> src/environments/environment.ts
        
        - name: Build & Push
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.CONTAINER_REGISTERY }}.azurecr.io
            username: ${{ secrets.AZURE_USERNAME }}
            password: ${{ secrets.AZURE_PASSWORD }}
        - run: |
            docker build . -t ${{ env.APP_NAME }}:1.0.${{ github.run_number }}
            docker tag ${{ env.APP_NAME }}:1.0.${{ github.run_number }} ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}
            docker push ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}

        - uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.WEBAPP_NAME }}
            images: ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}

        - name: logout
          run: |
            az logout
